version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:14.3
    restart: always
    environment:
      # Localdev user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # Localdev databases
      # It will create 'development' and 'test' databases
      - POSTGRES_CUSTOM_MULTI_DB=development,test
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.9
    restart: always
    environment:
      # Default user
      - PGADMIN_DEFAULT_EMAIL=pgadmin@mypetcode.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      # Service args
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5050
      # Servers config
      # It will be used to connect to postgres databases
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    ports:
      - "5050:5050"
    volumes:
      - ./pgadmin-servers-config.json:/pgadmin4/servers.json

volumes:
  db:
    driver: local
